### ISSUE TITLE
Suggestion: Organise docker configuration files in a docker folder

### ISSUE THREAD

**Issue by sergeifilippov** [eivindml/docker-craft-nginx#2]
What about organising docker image configuration files line `www.conf` inside a docker folder?

This will make the folder structure a little bit cleaner.

**Comment by eivindml** [comment]
Thank you for your input. This example was quickly created, but would love to make it cleaner. I also want it to be easily understandable what is going on. This was something I was missing when looking at other examples.

Is this normal to use a docker folder? Do you have other examples of repos doing it like this? 

I see that [this](https://github.com/zeit/now-examples/tree/master/php-laravel) repo has a `docker` folder.

[Here](https://github.com/zeit/now-examples/tree/master/php-wordpress) it is in a `src` folder. 

But it might be a good idea to add both a `docker` folder for `www.conf` and `nginx.conf`, and then a `src` folder for everything that will be copied over to the containers `/www` folder. What do you think?

**Comment by sergeifilippov** [comment]
> But it might be a good idea to add both a docker folder for www.conf and nginx.conf, and then a src folder for everything that will be copied over to the containers /www folder. What do you think?

Yeah sounds good to me.

What I also seen is people putting Docker-related files in a `.docker` folder also. I even seen breaking down files buy in the `.docker` folder by `environment` kinda like this:

```
.docker
    - local
        - nginx
            - nginx.conf
        ...
    - staging
        - ...
    - production
        ...
```
